export const APP_LOADING_TRANSITION_MS = 500;
// Well inside the server's DEVICE_LEASE_TTL_MS (60s).
export const DEVICE_LEASE_HEARTBEAT_MS = 20_000;
export const LIVE_CLOCK_TICK_MS = 1000;
export const SEARCH_DEBOUNCE_MS = 300;
export const CAPTURE_FLASH_MS = 300;
export const PRESENCE_TIMEOUT_MS = 8000;
export const CAPTURE_TIMEOUT_MS = 8000;
export const HEARTBEAT_INTERVAL_MS = 3000;
export const DOCUMENT_TITLE_CYCLE_MS = 4000;
export const APP_VERSION_CHECK_INTERVAL_MS = 15 * 60 * 1000;
export const TOUR_STEP_NAVIGATION_DELAY_MS = 60;
export const CALIBRATION_PREVIEW_DEBOUNCE_MS = 150;
export const SCAN_REGION_PHONE_SYNC_DELAY_MS = 80;
export const CALIBRATION_STEP_SETTLE_MS = 500;
export const FEEDER_PREVIEW_STOP_MS = 3000;
export const SERVO_TEST_GATE_HOLD_MS = 600;
export const SERVO_TEST_PUSHER_HOLD_MS = 1000;
export const CARD_DETECTION_RETRY_TIMEOUT_MS = 1000;
export const CARD_DETECTION_RETRY_INTERVAL_MS = 100;

export const ROUTE_RESPONSE_TIMEOUT_MS = 15_000;
export const ROUTE_WITH_FEED_RESPONSE_TIMEOUT_MS = 25_000;
export const PUSH_TEST_RESPONSE_TIMEOUT_MS = 12_000;
export const SETUP_IR_POLL_MS = 300;
export const SETUP_IR_RESPONSE_TIMEOUT_MS = 1000;
export const MONITOR_REFRESH_THROTTLE_MS = 1000;
export const BILLING_STALE_MS = 60_000;
export const STORE_CONFIG_TIMEOUT_MS = 10_000;
export const NEUTRAL_RESPONSE_TIMEOUT_MS = 5000;

export const APP_STREAM_GUID_DEBOUNCE_MS = 50;
export const ORG_OVERVIEW_REFRESH_MS = 60_000;
