export const SYNC_DATA_REFRESH_BATCH_SIZE = 500;
export const TCGPLAYER_PRICE_UPSERT_BATCH_SIZE = 1000;
export const TCGPLAYER_PRODUCT_UPSERT_BATCH_SIZE = 1000;
export const CARDMARKET_PRICE_UPSERT_BATCH_SIZE = 1000;
export const CARDMARKET_PRODUCT_UPSERT_BATCH_SIZE = 1000;
export const CARDKINGDOM_PRICE_UPSERT_BATCH_SIZE = 1000;

export const FAB_SYNC_PAGE_SIZE = 1000;
export const FAB_SYNC_LOG_EVERY = 250;

export const POKEMON_SYNC_PAGE_LIMIT = 1000;
export const POKEMON_DETAIL_CONCURRENCY = 8;
export const POKEMON_DETAIL_LOG_EVERY = 1000;
