import type { CalibrationTourStepConfig } from "@/lib/interfaces/tours";

export const CALIBRATION_TOUR_STEPS: CalibrationTourStepConfig[] = [
  {
    id: "welcome",
    section: "modules",
    target: "body",
    placement: "center",
    titleKey: "calibrationTour.welcome.title",
    contentKey: "calibrationTour.welcome.content",
  },
  {
    id: "sections",
    section: "modules",
    target: '[data-tour="calibration-sections"]',
    placement: "auto",
    titleKey: "calibrationTour.sections.title",
    contentKey: "calibrationTour.sections.content",
  },
  {
    id: "connect",
    section: "modules",
    target: '[data-tour="calibration-connect"]',
    placement: "auto",
    titleKey: "connectYourSorterTitle",
    contentKey: "calibrationTour.connect.content",
  },
  {
    id: "module-count",
    section: "modules",
    target: '[data-tour="module-count"]',
    placement: "auto",
    titleKey: "calibrationTour.moduleCount.title",
    contentKey: "calibrationTour.moduleCount.content",
  },
  {
    id: "bin-configurations",
    section: "modules",
    target: '[data-tour="bin-configurations"]',
    placement: "auto",
    titleKey: "calibrationTour.binConfigurations.title",
    contentKey: "calibrationTour.binConfigurations.content",
  },
  {
    id: "ir-sensor",
    section: "modules",
    target: '[data-tour="ir-sensor-panel"]',
    placement: "auto",
    titleKey: "calibrationTour.irSensor.title",
    contentKey: "calibrationTour.irSensor.content",
  },
  {
    id: "bin-routing-controls",
    section: "modules",
    target: '[data-tour="bin-routing-controls"]',
    placement: "auto",
    titleKey: "calibrationTour.binRoutingControls.title",
    contentKey: "calibrationTour.binRoutingControls.content",
  },
  {
    id: "scan-region",
    section: "scanRegion",
    target: '[data-tour="scan-region-panel"]',
    placement: "auto",
    titleKey: "calibrationTour.scanRegion.title",
    contentKey: "calibrationTour.scanRegion.content",
  },
  {
    id: "feeder",
    section: "calibration",
    target: '[data-tour="feeder-calibration-panel"]',
    placement: "auto",
    titleKey: "calibrationTour.feeder.title",
    contentKey: "calibrationTour.feeder.content",
  },
  {
    id: "module-calibration",
    section: "calibration",
    target: '[data-tour="module-calibration-grid"]',
    placement: "auto",
    titleKey: "calibrationTour.moduleCalibration.title",
    contentKey: "calibrationTour.moduleCalibration.content",
  },
  {
    id: "done",
    section: "calibration",
    target: "body",
    placement: "center",
    titleKey: "calibrationTour.done.title",
    contentKey: "calibrationTour.done.content",
  },
];
